use sea_orm::{
    ConnectionTrait, DatabaseBackend, DatabaseConnection, QueryResult, Statement, TransactionTrait,
};

use crate::MigrationError;

fn database_error(message: String, source: sea_orm::DbErr) -> MigrationError {
    MigrationError::Database {
        message,
        source: Some(Box::new(source)),
    }
}

/// Compiled migration with per-backend SQL byte arrays.
/// A single migration baked into the binary at compile time by the `vespertide_migration!` macro.
///
/// Each `EmbeddedMigration` holds three pre-compiled SQL blobs (one per supported backend).
/// Individual SQL statements within a blob are separated by null bytes (`\0`); use
/// [`split_sql_blob`] to iterate over them.
///
/// You do not construct `EmbeddedMigration` values manually. The `vespertide_migration!` macro
/// generates a `const` array of these and passes it to [`run_embedded_migrations`].
#[derive(Debug, Clone, Copy)]
pub struct EmbeddedMigration {
    /// Monotonically increasing version number matching the migration file.
    pub version: u32,
    /// UUID identifying this specific migration plan, used to detect history divergence.
    pub migration_id: &'static str,
    /// Human-readable description of what this migration does.
    pub comment: &'static str,
    /// Null-byte-delimited SQL statements for `PostgreSQL`.
    pub postgres_sql_blob: &'static str,
    /// Null-byte-delimited SQL statements for `MySQL`.
    pub mysql_sql_blob: &'static str,
    /// Null-byte-delimited SQL statements for `SQLite`.
    pub sqlite_sql_blob: &'static str,
}

impl EmbeddedMigration {
    /// Construct an embedded migration; called by the `vespertide_migration!` macro expansion. Not intended for hand-written use.
    pub const fn new(
        version: u32,
        migration_id: &'static str,
        comment: &'static str,
        postgres_sql_blob: &'static str,
        mysql_sql_blob: &'static str,
        sqlite_sql_blob: &'static str,
    ) -> Self {
        Self {
            version,
            migration_id,
            comment,
            postgres_sql_blob,
            mysql_sql_blob,
            sqlite_sql_blob,
        }
    }

    pub const fn sql_blob(self, backend: DatabaseBackend) -> &'static str {
        if matches!(backend, DatabaseBackend::MySql) {
            self.mysql_sql_blob
        } else if matches!(backend, DatabaseBackend::Sqlite) {
            self.sqlite_sql_blob
        } else {
            self.postgres_sql_blob
        }
    }
}

pub fn split_sql_blob(blob: &str) -> impl Iterator<Item = &str> {
    blob.split_terminator('\0').filter(|sql| !sql.is_empty())
}

pub async fn run_embedded_migrations(
    pool: &DatabaseConnection,
    version_table: &str,
    verbose: bool,
    migrations: &[EmbeddedMigration],
) -> Result<(), MigrationError> {
    let backend = pool.get_database_backend();
    let q = if matches!(backend, DatabaseBackend::MySql) {
        '`'
    } else {
        '"'
    };

    let create_table_sql = format!(
        "CREATE TABLE IF NOT EXISTS {q}{version_table}{q} (version INTEGER PRIMARY KEY, id TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
    );
    let stmt = Statement::from_string(backend, create_table_sql);
    pool.execute_raw(stmt)
        .await
        .map_err(|e| database_error(format!("Failed to create version table: {e}"), e))?;

    let alter_sql = format!("ALTER TABLE {q}{version_table}{q} ADD COLUMN id TEXT DEFAULT ''");
    let stmt = Statement::from_string(backend, alter_sql);
    let _ = pool.execute_raw(stmt).await;

    let txn = pool
        .begin()
        .await
        .map_err(|e| database_error(format!("Failed to begin transaction: {e}"), e))?;

    let select_sql = format!("SELECT MAX(version) as version FROM {q}{version_table}{q}");
    let stmt = Statement::from_string(backend, select_sql);
    let version_result = txn
        .query_one_raw(stmt)
        .await
        .map_err(|e| database_error(format!("Failed to read version: {e}"), e))?;
    let version_i32 = version_result
        .and_then(|row| row.try_get::<i32>("", "version").ok())
        .unwrap_or(0);
    // Migration versions are generated by Vespertide as non-negative u32 values;
    // treat a corrupt negative database value as no applied migration.
    let version = u32::try_from(version_i32).unwrap_or(0);

    let select_ids_sql = format!("SELECT version, id FROM {q}{version_table}{q}");
    let stmt = Statement::from_string(backend, select_ids_sql);
    let id_rows = txn
        .query_all_raw(stmt)
        .await
        .map_err(|e| database_error(format!("Failed to read version ids: {e}"), e))?;
    let version_ids = collect_version_ids(&id_rows);

    if verbose {
        eprintln!("[vespertide] Current database version: {version}");
    }

    for migration in migrations {
        if version >= migration.version {
            continue;
        }

        if let Some(db_id) = version_ids.get(&migration.version)
            && !migration.migration_id.is_empty()
            && !db_id.is_empty()
            && db_id != migration.migration_id
        {
            return Err(MigrationError::IdMismatch {
                version: migration.version,
                expected: migration.migration_id.to_string(),
                found: db_id.clone(),
            });
        }

        if verbose {
            eprintln!(
                "[vespertide] Applying migration v{} ({})",
                migration.version, migration.comment
            );
        }

        let sql_blob = migration.sql_blob(backend);
        let sqls: Vec<_> = split_sql_blob(sql_blob).collect();

        for (sql_idx, sql) in sqls.iter().enumerate() {
            if verbose {
                eprintln!("[vespertide]   [{}/{}] {}", sql_idx + 1, sqls.len(), sql);
            }

            let stmt = Statement::from_string(backend, (*sql).to_owned());
            txn.execute_raw(stmt)
                .await
                .map_err(|e| database_error(format!("Failed to execute SQL '{sql}': {e}"), e))?;
        }

        let insert_sql = format!(
            "INSERT INTO {q}{}{q} (version, id) VALUES ({}, '{}')",
            version_table, migration.version, migration.migration_id
        );
        let stmt = Statement::from_string(backend, insert_sql);
        txn.execute_raw(stmt)
            .await
            .map_err(|e| database_error(format!("Failed to insert version: {e}"), e))?;

        if verbose {
            eprintln!(
                "[vespertide] Migration v{} applied successfully",
                migration.version
            );
        }
    }

    txn.commit()
        .await
        .map_err(|e| database_error(format!("Failed to commit transaction: {e}"), e))?;

    Ok(())
}

fn collect_version_ids(rows: &[QueryResult]) -> std::collections::HashMap<u32, String> {
    let mut version_ids = std::collections::HashMap::new();
    for row in rows {
        if let Ok(found_version) = row.try_get::<i32>("", "version") {
            let id = row.try_get::<String>("", "id").unwrap_or_default();
            if let Ok(found_version) = u32::try_from(found_version) {
                version_ids.insert(found_version, id);
            }
        }
    }
    version_ids
}

#[cfg(test)]
mod tests {
    use std::error::Error;

    use sea_orm::{ConnectionTrait, Database, DatabaseBackend, Statement};

    use crate::MigrationError;

    use super::{EmbeddedMigration, run_embedded_migrations, split_sql_blob};

    async fn sqlite_memory_db() -> sea_orm::DatabaseConnection {
        Database::connect("sqlite::memory:").await.unwrap()
    }

    async fn read_versions(db: &sea_orm::DatabaseConnection) -> Vec<(i32, String)> {
        let stmt = Statement::from_string(
            DatabaseBackend::Sqlite,
            "SELECT version, id FROM \"vespertide_migrations\" ORDER BY version".to_owned(),
        );
        let rows = db.query_all_raw(stmt).await.unwrap();
        rows.into_iter()
            .map(|row| {
                (
                    row.try_get::<i32>("", "version").unwrap(),
                    row.try_get::<String>("", "id").unwrap(),
                )
            })
            .collect()
    }

    #[test]
    fn split_sql_blob_ignores_empty_segments() {
        let sqls: Vec<_> =
            split_sql_blob("CREATE TABLE users ();\0\0ALTER TABLE users;\0").collect();

        assert_eq!(sqls, vec!["CREATE TABLE users ();", "ALTER TABLE users;"]);
    }

    #[test]
    fn embedded_migration_selects_backend_blob() {
        let migration = EmbeddedMigration::new(1, "id", "comment", "pg\0", "mysql\0", "sqlite\0");

        assert_eq!(migration.sql_blob(DatabaseBackend::Postgres), "pg\0");
        assert_eq!(migration.sql_blob(DatabaseBackend::MySql), "mysql\0");
        assert_eq!(migration.sql_blob(DatabaseBackend::Sqlite), "sqlite\0");
    }

    #[test]
    fn db_err_conversion_preserves_source_chain() {
        let db_err = sea_orm::DbErr::Custom("connection refused".to_owned());
        let err = MigrationError::from(db_err);

        assert_eq!(
            err.to_string(),
            "database error: Custom Error: connection refused"
        );
        assert!(err.source().is_some());
        assert!(matches!(
            &err,
            MigrationError::Database {
                source: Some(_),
                ..
            }
        ));
        assert!(
            err.source()
                .is_some_and(|source| source.to_string() == "Custom Error: connection refused")
        );
    }

    #[tokio::test]
    async fn run_embedded_migrations_applies_pending_versions_and_records_ids() {
        let db = sqlite_memory_db().await;
        let migrations = [
            EmbeddedMigration::new(
                1,
                "init",
                "create users",
                "CREATE TABLE users (id INTEGER PRIMARY KEY);\0",
                "CREATE TABLE users (id INTEGER PRIMARY KEY);\0",
                "CREATE TABLE users (id INTEGER PRIMARY KEY);\0",
            ),
            EmbeddedMigration::new(
                2,
                "add_name",
                "add name column",
                "ALTER TABLE users ADD COLUMN name TEXT;\0",
                "ALTER TABLE users ADD COLUMN name TEXT;\0",
                "ALTER TABLE users ADD COLUMN name TEXT;\0",
            ),
        ];

        run_embedded_migrations(&db, "vespertide_migrations", true, &migrations)
            .await
            .unwrap();

        let versions = read_versions(&db).await;
        assert_eq!(
            versions,
            vec![(1, "init".to_string()), (2, "add_name".to_string())]
        );

        let stmt = Statement::from_string(
            DatabaseBackend::Sqlite,
            "PRAGMA table_info('users')".to_owned(),
        );
        let rows = db.query_all_raw(stmt).await.unwrap();
        let names: Vec<_> = rows
            .into_iter()
            .map(|row| row.try_get::<String>("", "name").unwrap())
            .collect();
        assert_eq!(names, vec!["id".to_string(), "name".to_string()]);
    }

    #[tokio::test]
    async fn run_embedded_migrations_skips_versions_that_are_already_applied() {
        let db = sqlite_memory_db().await;
        run_embedded_migrations(
            &db,
            "vespertide_migrations",
            false,
            &[EmbeddedMigration::new(
                1,
                "init",
                "create users",
                "CREATE TABLE users (id INTEGER PRIMARY KEY);\0",
                "CREATE TABLE users (id INTEGER PRIMARY KEY);\0",
                "CREATE TABLE users (id INTEGER PRIMARY KEY);\0",
            )],
        )
        .await
        .unwrap();

        run_embedded_migrations(
            &db,
            "vespertide_migrations",
            true,
            &[
                EmbeddedMigration::new(
                    1,
                    "init",
                    "should skip existing",
                    "ALTER TABLE users ADD COLUMN skipped TEXT;\0",
                    "ALTER TABLE users ADD COLUMN skipped TEXT;\0",
                    "ALTER TABLE users ADD COLUMN skipped TEXT;\0",
                ),
                EmbeddedMigration::new(
                    2,
                    "add_name",
                    "apply only new version",
                    "ALTER TABLE users ADD COLUMN name TEXT;\0",
                    "ALTER TABLE users ADD COLUMN name TEXT;\0",
                    "ALTER TABLE users ADD COLUMN name TEXT;\0",
                ),
            ],
        )
        .await
        .unwrap();

        let versions = read_versions(&db).await;
        assert_eq!(
            versions,
            vec![(1, "init".to_string()), (2, "add_name".to_string())]
        );

        let stmt = Statement::from_string(
            DatabaseBackend::Sqlite,
            "PRAGMA table_info('users')".to_owned(),
        );
        let rows = db.query_all_raw(stmt).await.unwrap();
        let names: Vec<_> = rows
            .into_iter()
            .map(|row| row.try_get::<String>("", "name").unwrap())
            .collect();
        assert!(!names.iter().any(|name| name == "skipped"));
        assert!(names.iter().any(|name| name == "name"));
    }

    #[tokio::test]
    async fn run_embedded_migrations_surfaces_sql_errors() {
        let db = sqlite_memory_db().await;
        let stmt = Statement::from_string(DatabaseBackend::Sqlite, "CREATE TABLE \"vespertide_migrations\" (version INTEGER PRIMARY KEY, id TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)".to_owned());
        db.execute_raw(stmt).await.unwrap();
        let stmt = Statement::from_string(
            DatabaseBackend::Sqlite,
            "INSERT INTO \"vespertide_migrations\" (version, id) VALUES (2, 'different')"
                .to_owned(),
        );
        db.execute_raw(stmt).await.unwrap();

        let result = run_embedded_migrations(
            &db,
            "vespertide_migrations",
            true,
            &[EmbeddedMigration::new(
                3,
                "broken",
                "invalid sql",
                "THIS IS NOT SQL;\0",
                "THIS IS NOT SQL;\0",
                "THIS IS NOT SQL;\0",
            )],
        )
        .await;

        let err = result.unwrap_err();
        assert!(err.source().is_some());
        assert!(matches!(
            err,
            MigrationError::Database { message, source: Some(_) }
                if message.contains("Failed to execute SQL 'THIS IS NOT SQL;'")
        ));
    }

    #[tokio::test]
    async fn run_embedded_migrations_detects_existing_version_id_mismatch() {
        let db = sqlite_memory_db().await;
        let stmt = Statement::from_string(DatabaseBackend::Sqlite, "CREATE TABLE \"vespertide_migrations\" (version INTEGER PRIMARY KEY, id TEXT DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)".to_owned());
        db.execute_raw(stmt).await.unwrap();
        let stmt = Statement::from_string(
            DatabaseBackend::Sqlite,
            "INSERT INTO \"vespertide_migrations\" (version, id) VALUES (2, 'different')"
                .to_owned(),
        );
        db.execute_raw(stmt).await.unwrap();
        let stmt = Statement::from_string(
            DatabaseBackend::Sqlite,
            "INSERT INTO \"vespertide_migrations\" (version, id) VALUES (2147483648, 'overflow')"
                .to_owned(),
        );
        db.execute_raw(stmt).await.unwrap();

        let result = run_embedded_migrations(
            &db,
            "vespertide_migrations",
            true,
            &[EmbeddedMigration::new(
                2,
                "expected",
                "mismatch",
                "ALTER TABLE users ADD COLUMN name TEXT;\0",
                "ALTER TABLE users ADD COLUMN name TEXT;\0",
                "ALTER TABLE users ADD COLUMN name TEXT;\0",
            )],
        )
        .await;

        assert!(matches!(
            result,
            Err(MigrationError::IdMismatch {
                version: 2,
                expected,
                found,
            }) if expected == "expected" && found == "different"
        ));
    }
}
