mod display;
mod prefix;

#[cfg(test)]
mod tests;

use crate::schema::{ColumnDef, ColumnName, ColumnType, TableConstraint, TableName};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// A single versioned migration, grouping a set of [`MigrationAction`]s under a version number.
///
/// Migration plans are auto-generated by `vespertide revision` and stored as JSON or YAML files
/// in the `migrations/` directory. **Never create or edit these files manually.**
///
/// The `version` field is a monotonically increasing integer. The `id` is a UUID that guards
/// against accidental plan substitution when the same version number appears in two different
/// migration histories.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(rename_all = "snake_case")]
pub struct MigrationPlan {
    /// Unique identifier for this migration (UUID format).
    /// Defaults to empty string for backward compatibility with old migration files.
    #[serde(default)]
    pub id: String,
    /// Human-readable description of what this migration does (from `-m "message"`).
    pub comment: Option<String>,
    /// ISO 8601 timestamp of when the migration file was generated.
    #[serde(default)]
    pub created_at: Option<String>,
    /// Monotonically increasing version number, starting at 1.
    pub version: u32,
    /// Ordered list of schema changes to apply in this migration.
    pub actions: Vec<MigrationAction>,
}

/// A single schema change produced by the planner and consumed by the SQL generator.
///
/// The planner emits a `Vec<MigrationAction>` when diffing two schemas. The SQL generator
/// (`vespertide-query`) translates each action into backend-specific DDL statements.
///
/// Prefer typed actions over [`MigrationAction::RawSql`]. Raw SQL is an emergency escape hatch:
/// it is not portable across backends and is skipped during baseline replay, which means the
/// planner cannot reason about it.
///
/// This enum is `#[non_exhaustive]`: new variants may be added in future releases.
/// Downstream `match` expressions should include a wildcard arm.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum MigrationAction {
    /// Create a new table with the given columns and constraints (`CREATE TABLE`).
    CreateTable {
        table: TableName,
        columns: Vec<ColumnDef>,
        constraints: Vec<TableConstraint>,
    },
    /// Drop an existing table and all its data (`DROP TABLE`).
    DeleteTable { table: TableName },
    /// Add a new column to an existing table (`ALTER TABLE ... ADD COLUMN`).
    AddColumn {
        table: TableName,
        column: Box<ColumnDef>,
        /// Optional fill value to backfill existing rows when adding NOT NULL without default.
        fill_with: Option<String>,
    },
    /// Rename a column in an existing table (`ALTER TABLE ... RENAME COLUMN`).
    RenameColumn {
        table: TableName,
        from: ColumnName,
        to: ColumnName,
    },
    /// Remove a column from an existing table (`ALTER TABLE ... DROP COLUMN`).
    DeleteColumn {
        table: TableName,
        column: ColumnName,
    },
    /// Change the SQL type of an existing column (`ALTER TABLE ... ALTER COLUMN ... TYPE`).
    ModifyColumnType {
        table: TableName,
        column: ColumnName,
        new_type: ColumnType,
        /// Mapping of removed enum values to replacement values for safe enum value removal.
        /// e.g., `{"cancelled": "'pending'"}` generates an `UPDATE` before the type change.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        fill_with: Option<BTreeMap<String, String>>,
    },
    /// Change whether a column accepts `NULL` values.
    ModifyColumnNullable {
        table: TableName,
        column: ColumnName,
        nullable: bool,
        /// Required when changing from nullable to non-nullable to backfill existing NULL values.
        fill_with: Option<String>,
        /// When true, rows with NULL values in the column are deleted instead of backfilled.
        /// Mutually exclusive with `fill_with`. Useful for FK columns where a valid fill value
        /// may not exist.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        delete_null_rows: Option<bool>,
    },
    /// Change or remove the default value of a column.
    ModifyColumnDefault {
        table: TableName,
        column: ColumnName,
        /// The new default value, or `None` to remove the default.
        new_default: Option<String>,
    },
    /// Change or remove the comment on a column.
    ModifyColumnComment {
        table: TableName,
        column: ColumnName,
        /// The new comment, or `None` to remove the comment.
        new_comment: Option<String>,
    },
    /// Add a constraint (primary key, unique, foreign key, check, or index) to a table.
    AddConstraint {
        table: TableName,
        constraint: TableConstraint,
    },
    /// Remove a constraint from a table.
    RemoveConstraint {
        table: TableName,
        constraint: TableConstraint,
    },
    /// Atomically replace one constraint with another (e.g. when columns in a composite key change).
    ReplaceConstraint {
        table: TableName,
        from: TableConstraint,
        to: TableConstraint,
    },
    /// Rename a table (`ALTER TABLE ... RENAME TO`).
    RenameTable { from: TableName, to: TableName },
    /// Execute a raw SQL statement verbatim.
    ///
    /// **Emergency escape hatch only.** Raw SQL is not portable across backends and is invisible
    /// to baseline replay, so the planner cannot reason about schema state after this action.
    /// Use typed actions whenever possible.
    RawSql { sql: String },
}

impl MigrationAction {
    /// Returns the primary table this action affects, if any.
    /// Returns None for actions that don't bind to a single table (e.g. `RawSql`).
    #[must_use]
    pub fn table_name(&self) -> Option<&str> {
        match self {
            Self::CreateTable { table, .. }
            | Self::DeleteTable { table }
            | Self::AddColumn { table, .. }
            | Self::DeleteColumn { table, .. }
            | Self::RenameColumn { table, .. }
            | Self::ModifyColumnType { table, .. }
            | Self::ModifyColumnNullable { table, .. }
            | Self::ModifyColumnDefault { table, .. }
            | Self::ModifyColumnComment { table, .. }
            | Self::AddConstraint { table, .. }
            | Self::RemoveConstraint { table, .. }
            | Self::ReplaceConstraint { table, .. } => Some(table.as_str()),
            Self::RenameTable { from, .. } => Some(from.as_str()),
            Self::RawSql { .. } => None,
        }
    }
}
